name: xray-warp-ct multiplatform build staging

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: True
        type: string
      DOCKERHUB_REGISTRY:
        required: True
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: True

jobs:
  xray-staging-image:
    runs-on: ubuntu-latest
    outputs:
      get_date: ${{ steps.date.outputs.CURRENT_DATE }}
    steps:
      - id: date
        run: echo "CURRENT_DATE=$(date "+%Y-%m-%d")" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      # Docker buildx steps
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64, linux/amd64
          context: .
          push: true
          tags: |
            ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.DOCKERHUB_REGISTRY }}:staging
            ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.DOCKERHUB_REGISTRY }}:staging-${{ steps.date.outputs.CURRENT_DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
