name: "Terraform Destroy"

on:
  workflow_call:
    inputs:
      CONFIG_DIRECTORY:
        required: True
        type: string
    secrets:
      TF_API_TOKEN:
        required: False
      DOMAIN_NAME:
        required: false
      CLOUDFLARE_TOKEN:
        required: false

env:
  TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"
  TF_VAR_domain_name: "${{ secrets.DOMAIN_NAME }}"
  TF_VAR_cloudflare_token: "${{ secrets.CLOUDFLARE_TOKEN }}"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.CONFIG_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - id: destroy
        run: terraform destroy --auto-approve
