name: "Terraform Destroy"

on:
  workflow_call:
    inputs:
      CONFIG_DIRECTORY:
        required: True
        type: string
    secrets:
      TF_CLOUD_ORGANIZATION:
        required: True
      TF_API_TOKEN:
        required: True
      TF_WORKSPACE:
        required: True

env:
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
  CONFIG_DIRECTORY: ${{ inputs.CONFIG_DIRECTORY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - id: destroy
        run: terraform destroy --auto-approve
