name: "Terraform Destroy"

on:
  workflow_call:
    inputs:
      CONFIG_DIRECTORY:
        required: True
        type: string
    secrets:
      TF_API_TOKEN:
        required: True

env:
  TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - run: cd ${{ inputs.CONFIG_DIRECTORY }}
      - run: terraform init
      - id: destroy
        run: terraform destroy --auto-approve
