name: docker-multiplatform-build-dev

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

jobs:
  docker:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Get the current date
        run: | 
          echo "CURRENT_DATE=$(date "+%Y-%m-%d")" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REGISTRY }}:staging
            ${{ vars.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REGISTRY }}:staging-${{ env.CURRENT_DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max