name: terraform apply

on:
  workflow_call:
    inputs:
      CONFIG_DIRECTORY:
        required: True
        type: string
    secrets:
      TF_API_TOKEN:
        required: True
      DOMAIN_NAME:
        required: true
      CLOUDFLARE_TOKEN:
        required: true
      TLS_CERT_BASE64:
        required: false
      TLS_KEY_BASE64:
        required: false

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"
      TF_VAR_domain_name: "${{ secrets.DOMAIN_NAME }}"
      TF_VAR_cloudflare_token: "${{ secrets.CLOUDFLARE_TOKEN }}"
      TF_VAR_tls_cert_base64: ${{ secrets.TLS_CERT_BASE64 }}
      TF_VAR_tls_key_base64: ${{ secrets.TLS_KEY_BASE64 }}
    defaults:
      run:
        working-directory: ${{ inputs.CONFIG_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - id: apply
        run: terraform apply --auto-approve
    needs: [base64-encode-tls-cert-and-key]
