name: obtain-tls-certificate
#on:
#  schedule:
#    - cron: "0 22 * * 4"

on: workflow_dispatch

env:
  CLOUDFLARE_DNS_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  ACME_ACCOUNT: ${{ secrets.ACME_ACCOUNT }}
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  obtain-tls-certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create tls cert and key
        run: |
          ./helpers_scripts/obtain-cert.sh
          mkdir -p $GITHUB_WORKSPACE/certs
          sudo cp /var/snap/lego/common/.lego/certificates/$DOMAIN_NAME.crt $GITHUB_WORKSPACE/certs/$DOMAIN_NAME.crt
          sudo cp /var/snap/lego/common/.lego/certificates/$DOMAIN_NAME.key $GITHUB_WORKSPACE/certs/$DOMAIN_NAME.key
          sudo chown $USER:$USER $GITHUB_WORKSPACE/certs/*
      - name: Export tls cert and key to github secrets
        run: |
          gh secret set TLS_CERT_BASE64 --body "$(base64 -w0 $GITHUB_WORKSPACE/certs/$DOMAIN_NAME.crt)"
          gh secret set TLS_KEY_BASE64 --body "$(base64 -w0 $GITHUB_WORKSPACE/certs/$DOMAIN_NAME.key)"
