name: obtain-tls-certificate
#on:
#  schedule:
#    - cron: "0 22 * * 4"

on: workflow_dispatch

env:
  CLOUDFLARE_DNS_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  ACME_ACCOUNT: ${{ secrets.ACME_ACCOUNT }}

jobs:
  obtain-tls-certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "chmod obtain-cert.sh script"
        run: chmod +x ./helpers_scripts/obtain-cert.sh
      - name: "Create tls certificate"
        run: ./helpers_scripts/obtain-cert.sh
      - name: upload tls cert and key
        uses: actions/upload-artifact@v4
        with:
          name: tls-cert-and-key-artifact
          path: |
            /var/snap/lego/common/.lego/certificates/${{ secrets.DOMAIN_NAME }}.crt
            /var/snap/lego/common/.lego/certificates/${{ secrets.DOMAIN_NAME }}.crt
