name: xray-warp-ct staging CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  build-stage-image:
    uses: ./.github/workflows/actions/build-staging.yaml
    with:
      DOCKERHUB_USERNAME: xia1997x
      DOCKERHUB_REGISTRY: xray-warp-staging
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  setup-staging-environment:
    uses: ./.github/workflows/actions/setup-environment-staging.yaml
    with:
      CONFIG_DIRECTORY: "./tests/infrastructure"
    secrets:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
