name: xray-warp-ct staging CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  build-stage-image:
    uses: ./.github/workflows/build-staging.yaml
    with:
      DOCKERHUB_USERNAME: xia1997x
      DOCKERHUB_REGISTRY: xray-warp-staging
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
